### ISSUE TITLE
Fix for the missing translation in the Smugglers Point scenario's Polish localization.

### ISSUE THREAD

**Issue by adrkakol** [antontimmermans/MOMSP#3]
Hello @antontimmermans 

I prepared a fix for a missing translation in the Polish translation.
You can just change the file to the one I attached.

I hope you will be able to release the fix.

Requested change:
```diff
- EventDoorLampTowerGhostDead.text,With the ghost gone, the strange glow on the door has also disappeared.
+ EventDoorLampTowerGhostDead.text,Teraz, gdy duch Zadoka zniknął, zauważasz, że dziwna poświata bijąca od drzwi także zniknęła.
```

File with the fix:

[Localization.Polish.txt](https://github.com/antontimmermans/MOMSP/files/5380639/Localization.Polish.txt)

Screenshot of the missing translation:

<img width="500" alt="Screenshot 2020-10-14 at 20 51 49" src="https://user-images.githubusercontent.com/20544983/96040750-1ca81880-0e6b-11eb-9868-47e4c1c7d4bf.png">

**Comment by antontimmermans** [comment]
Thank you very much for this fix. It will be released no later than Oct 24th,  together with another potential fix in the Polish translation (I need to get the second fix confirmed first.

**Comment by antontimmermans** [comment]
fixed and released

**Comment by adrkakol** [comment]
Thanks! Cheers
