### ISSUE TITLE
Czech translate

### ISSUE THREAD

**Issue by LabBrab** [antontimmermans/MOMSP#5]
Hi Anton,

I translated your next scenario - Smugglers Point v1.4 into Czech language. I am attaching the file. I'll be happy if you add him to Valkyrie soon.

Best regards

LabBrab

[Localization.Czech.txt](https://github.com/antontimmermans/MOMSP/files/13895226/Localization.Czech.txt)

**Comment by antontimmermans** [comment]
Translation added and released
Thanks again for your hard work
